language: node_js
node_js:
  - "0.12"

before_script:
  - npm install
  - cd server
  - npm install --quiet
  - node app/app.js
  - sleep 3 # give server some time to start
  - cd ../client
  - npm install --quiet

script: